version: "3"
services:
  hello:
    image: edtasixm11/k19:hello
    deploy:
      replicas: 3            
    ports:
      - "80:80"            
    networks:
      - mynet
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynet
networks:
  mynet:
